import React, { useEffect } from "react";

const Cookies = () => {
  useEffect(() => {
    const toTop = () => {
      window.scrollTo(0, 0);
    };

    return () => {
      toTop();
    };
  }, []);

  return (
    <div>
      <div className="bg-gradient-to-r from-[#444DA1] to-[#2068FF]">
        <div className="py-8 px-6 md:py-10 md:px-14 lg:px-20 xl:px-24">
          <h2 className="text-white text-xl md:text-3xl lg:text-4xl font-bold">
            Cookies
          </h2>
        </div>
      </div>

      <div className="py-8 px-6 md:py-10 md:px-14 lg:px-20 xl:px-24 flex flex-col gap-10">
        <div className="flex flex-col gap-3 ">
          <p>
            Cookies are small text files placed on your device when you visit a
            website. They are generated by a web page server and can be used by
            that server whenever the user visits the site.
          </p>
        </div>
        <div className="flex flex-col gap-3">
          <h4 className="text-lg md:text-2xl font-medium text-[color:var(--blue)]">
            <span className="text-black">At</span> rework
          </h4>
          <p>
            We combine the power of today’s technology with the passion of our
            HR professionals to create an experience that’s inherently more
            human. To achieve this goal we use technology to our advantage,
            including cookies.
          </p>
          <p>
            Cookies help us to provide a seamless browsing experience by
            recognising you each time you visit the site and helping our team to
            understand what parts of the website you find most interesting and
            useful.
          </p>
          <p>
            The cookie settings on this site are set to ‘allow all’– but if you
            want, you can change your settings at any time. Please keep in mind
            that if you do, you may lose some functionality.
          </p>
          <p>More information can be found in our Cookie statement below.</p>
        </div>
        <div className="flex flex-col gap-4">
          <h4 className="text-lg md:text-2xl font-medium text-[color:var(--blue)]">
            Cookie Statement
          </h4>
          <p>
            You are at www.rework.io, the website of Rework Pvt Ltd hereinafter
            referred to as ‘Rework’ or “we”.
          </p>
          <p>Our website (www.rework.in) and its subdomains use cookies.</p>
          <p>
            Cookies are small text files that will be stored in your device
            (computer, tablet or mobile phone) via your browser primarily to
            enhance the convenience of using the site, to enable certain
            functions and to make visiting our website attractive. Third parties
            can also place cookies and similar techniques to monitor your
            internet behavior and show your personalized advertisements outside
            our website.The information in the cookies relates to your device,
            your browser and to the way you flip through our content and is not
            linked to your name, address or e-mail address.
          </p>

          <div>
            <h5 className="text-[color:var(--blue)]">
              which cookies do we use and why?
            </h5>
            <p>
              To the extent personal information may be collected using cookies,
              such information will only be processed in accordance to our
              privacy statement. which cookies do we use and why? Cookies can be
              placed by directly by our website or by third parties with whom we
              cooperate to help us diagnose technical problems, analyze the
              traffic to our website, analyze trends, observe and measure how
              our visitors engage with our website and identify preferences.
            </p>
          </div>
          <div className="flex flex-col gap-3">
            <h5 className="text-[color:var(--blue)]">Default cookies</h5>
            <p>
              These cookies are essential in order to enable you to move around
              the website and use its features, such as accessing secure areas
              of the website. Without these cookies services, you have asked
              for, like logging in, cannot be provided.
            </p>
            <p>
              Our website uses Google Analytics, provided by Google, Inc. and
              Optimizely, provided by Optimizely inc. These cookies are
              essential to provide you a seamless browser experience. They
              provide us with information on how you use the website and allow
              us to test various parts of the website.
            </p>
          </div>
          <div>
            <h5 className="text-[color:var(--blue)]">Functional cookies</h5>
            <p>
              Functional cookies. These cookies enable the website to provide
              enhanced functionality and personalization. They may be set by us
              or by third-party providers whose services we have added to our
              pages. If you do not allow these cookies then some or all of these
              services may not function properly.
            </p>
          </div>
          <div className="flex flex-col gap-3">
            <h5 className="text-[color:var(--blue)]">Performance cookies</h5>
            <p>
              These cookies collect information about how visitors use a
              website, for instance, which pages visitors go to most often, and
              if they get error messages from web pages. Only Randstad has
              access to the data collected via these cookies and we do not make
              these data available to third parties.
            </p>
            <p>
              Our website uses Hotjar, provided by Hotjar Ltd.; and HubSpot
              provided by HubSpot inc.
            </p>
            <p>
              advertising or targeting cookies. These cookies are used to
              deliver adverts more relevant to you and your interests They are
              also used to limit the number of times you see an advertisement as
              well as help measure the effectiveness of the advertising
              campaign. They are usually placed by advertising networks with the
              website operator’s permission. They remember that you have visited
              a website and this information is shared with other organizations
              such as advertisers. Quite often targeting or advertising cookies
              will be linked to site functionality provided by the other
              organization including social media services that we have added to
              the site to enable you to share our content.
            </p>
            <p>
              change your preference regarding cookies. You can prevent your
              browser to store cookie and/or delete the cookies from your device
              at any time via the browser settings. Please consult the ‘Help’
              section on your internet browser for instructions on this.
            </p>
            <p>
              If you choose to not accept cookies, you should be aware that you
              may no longer be able to make use of all possibilities and
              functionalities of our website, and that certain parts of the
              website may also no longer be visible or accessible.
            </p>
            <p>
              To opt-out from Google Analytics cookies at any time, you can also
              install the Google Analytics opt-out browser add-on.
            </p>
            <p>To opt-out from Optimizely, you can visit their opt-out page.</p>
            Your can also opt-out from Hotjar cookies at any time by visiting
            Hotjar opt-out page and clicking 'Disable Hotjar'. storage period.
            Most of the cookies we use will be deleted when you end the browser
            session (so-called session cookies). Other cookies will remain
            stored in your device longer, for a period of 2 years, with the
            exception of the web analytics cookies which can be stored in your
            device maximum of 10 years. changes to the cookies statement. We may
            update the Cookies Statement from time to time. You can see the date
            on which the last change was made below in this statement. We advise
            you to review our Cookies Statement on a regular basis so that you
            are aware of any changes. This statement was updated on: 25 May 2018
          </div>
        </div>
      </div>
    </div>
  );
};

export default Cookies;
